name: swe-agent
dependencies:
  - python=3.9
  - pip
  - pip:
    - anthropic
    - config
    - datasets
    - docker
    - gymnasium
    - numpy
    - openai>=1.0
    - pandas
    - rich
    - ruamel.yaml
    - swebench>=1.0.1
    - tenacity
    - unidiff
    - simple-parsing
    - together
    - ollama
    - rich-argparse
    - google-cloud-aiplatform
    - networkx==3.2.1
    - diskcache==5.6.3
    - grep-ast==0.2.4
    - prompt-toolkit==3.0.43
    - scipy==1.11.4
